### PR TITLE
Update child-parent.json

### PR DESCRIPTION
**Pull request by andreasronit**
Parent/Caregiver

### CODE REVIEW

**Comment by jonathanargentiero** [comment]
ok perfect, this one is to merge your `patch-1` into `master`. You can merge it right away because it's on your own private fork.

**Comment by jonathanargentiero** [comment]
perfect

**Comment by jonathanargentiero** [comment]
no you can make another one from `andreasronit/master` to `cfqr-data/master`. But you should not merge it right away, wait for automatic tests

**Comment by andreasronit** [comment]
Haha. It is a bit monkey see monkey do here. 
I have created another pull request for the parent version I believe. 
Are you gonna double check the json files?

A

**Comment by jonathanargentiero** [comment]
yup. 
BONUS: you can delete `patch-1` when the PR is closed.
https://github.com/andreasronit/cfqr-data/branches

**Pull request merged**
