### PR TITLE
Update teen-adult.json

### PR DESCRIPTION
**Pull request by andreasronit**
Hey J. I have made the translation for the teen/adult version now.

I wasn't totally sure how to deal with the "doesnt appl"y box in question 51 and "go to question 44" under question 42, but you can take a look.

I have treated the doesnt apply box as an additional fifth option for the entire group en block.
For the "go to question 44" part, I think this is for you to code...

A

### CODE REVIEW

**Comment by jonathanargentiero** [comment]
@andreasronit good chioce. Treat it as another option in the translations for the moment. We can make modifications laters for that if it doesn't go well with that.

Anyway pay attention you have 2 comma errors on line 4 (missing comma) and line 137 (missing comma).

PS: to notify me use @jonathanargentiero, otherwise I won't see your message.

**Comment by andreasronit** [comment]
@jonathanargentiero 
Ok I didnt know that. Sorry. I have already merged with the stem.

**Comment by andreasronit** [comment]
@jonathanargentiero
When I look under CFQR/cfqr-data it appears as if there are still no amendments to the teenage/adult translation

**Comment by jonathanargentiero** [comment]
@andreasronit because now you should do a merge request from `andreasronit/master` to `cfqr-data/master`.

**Comment by andreasronit** [comment]
@jonathanargentiero 
We dont know how to do a merge request?

**Comment by jonathanargentiero** [comment]
@andreasronit sorry, merge request is the same as pull request :dancer:

**Pull request merged**
